export const bolts = {
  series: "Rod Bolts: Chevrolet Small Block 327 cubic inch",
  list: [
    [
      { name: "ID", value: "134-6001" },
      { name: "Model", value: "full set" },
      { name: "Material", value: "8740 Chrome Moly" },
      { name: "Tensile Strength", value: "18,0000 psi" },
      { name: "Finish", value: "Black Oxide" },
      { name: "Shank Type", value: "Knurled Shank" },
      { name: "Socket Size", value: "1/2 inch" },
      { name: "Socket Type", value: "hex" },
      { name: "Head Style", value: "/assets/head.png" },
      { name: "Underhead Length", value: "2.500 inch" },
      { name: "Diameter", value: "9/16-20" },
      { name: "Thread Length", value: "0.950 inch" },
      { name: "Grip Length", value: "1/250 inch" },
      { name: "Head Height", value: "0.350 inch" },
      { name: "Collar Diameter", value: "0.625 inch" },
      { name: "Pieces", value: "16 bolts, 16 nuts" },
      { name: "Weight", value: "135 g" },
      { name: "Image", value: "/assets/set.png" },
    ],
    [
      { name: "ID", value: "134-6002" },
      { name: "Model", value: "full set" },
      { name: "Material", value: "8740 Chrome Moly" },
      { name: "Tensile Strength", value: "18,0000 psi" },
      { name: "Finish", value: "Black Oxide" },
      { name: "Shank Type", value: "Knurled Shank" },
      { name: "Socket Size", value: "1/2 inch" },
      { name: "Socket Type", value: "hex" },
      { name: "Head Style", value: "/assets/head.png" },
      { name: "Underhead Length", value: "2.500 inch" },
      { name: "Diameter", value: "9/16-20" },
      { name: "Thread Length", value: "0.950 inch" },
      { name: "Grip Length", value: "1/250 inch" },
      { name: "Head Height", value: "0.350 inch" },
      { name: "Collar Diameter", value: "0.625 inch" },
      { name: "Pieces", value: "16 bolts, 16 nuts" },
      { name: "Weight", value: "135 g" },
      { name: "Image", value: "/assets/set.png" },
    ],
    [
      { name: "ID", value: "134-6003" },
      { name: "Model", value: "full set" },
      { name: "Material", value: "8740 Chrome Moly" },
      { name: "Tensile Strength", value: "18,0000 psi" },
      { name: "Finish", value: "Black Oxide" },
      { name: "Shank Type", value: "Knurled Shank" },
      { name: "Socket Size", value: "1/2 inch" },
      { name: "Socket Type", value: "hex" },
      { name: "Head Style", value: "/assets/head.png" },
      { name: "Underhead Length", value: "2.500 inch" },
      { name: "Diameter", value: "9/16-20" },
      { name: "Thread Length", value: "0.950 inch" },
      { name: "Grip Length", value: "1/250 inch" },
      { name: "Head Height", value: "0.350 inch" },
      { name: "Collar Diameter", value: "0.625 inch" },
      { name: "Pieces", value: "16 bolts, 16 nuts" },
      { name: "Weight", value: "135 g" },
      { name: "Image", value: "/assets/set.png" },
    ],
    [
      { name: "ID", value: "134-6004" },
      { name: "Model", value: "full set" },
      { name: "Material", value: "8740 Chrome Moly" },
      { name: "Tensile Strength", value: "18,0000 psi" },
      { name: "Finish", value: "Black Oxide" },
      { name: "Shank Type", value: "Knurled Shank" },
      { name: "Socket Size", value: "1/2 inch" },
      { name: "Socket Type", value: "hex" },
      { name: "Head Style", value: "/assets/head.png" },
      { name: "Underhead Length", value: "2.500 inch" },
      { name: "Diameter", value: "9/16-20" },
      { name: "Thread Length", value: "0.950 inch" },
      { name: "Grip Length", value: "1/250 inch" },
      { name: "Head Height", value: "0.350 inch" },
      { name: "Collar Diameter", value: "0.625 inch" },
      { name: "Pieces", value: "16 bolts, 16 nuts" },
      { name: "Weight", value: "135 g" },
      { name: "Image", value: "/assets/set.png" },
    ],
  ],
};
